AplicacaoTeste/Models/ContatosModel.cs
namespace AplicacaoTeste.Models
{
    public class ContatosModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }

        public string Telefone { get; set;}
        public string Email {  get; set; }

    }
}

AplicacaoTeste/Models/ErrorViewModel.cs
namespace AplicacaoTeste.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AplicacaoTeste/Controllers/ContatosController.cs
using AplicacaoTeste.Models;
using AplicacaoTeste.Repositorios;
using Microsoft.AspNetCore.Mvc;

namespace AplicacaoTeste.Controllers
{
    public class ContatosController : Controller
    {
        private readonly IContatoRepositorio _contatoRepositorio;
        public ContatosController(IContatoRepositorio contato)
        {
            _contatoRepositorio = contato;
        }
        public IActionResult Index()
        {
            List<ContatosModel> contatos = _contatoRepositorio.GetContatos();
            return View(contatos);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult DeletarConfirmacao(int id)
        {
            ContatosModel contato = _contatoRepositorio.ListarPorId(id);
            return View(contato);
        }

        public IActionResult Editar(int id)
        {
            ContatosModel contato = _contatoRepositorio.ListarPorId(id);
            return View(contato);
        }

        [HttpPost]
        public IActionResult Criar(ContatosModel contato)
        {
            _contatoRepositorio.Adicionar(contato);
            return RedirectToAction("Index");

        }
        [HttpPost]
        public IActionResult Atualizar(ContatosModel contato)
        {
            _contatoRepositorio.Atualizar(contato);
            return RedirectToAction("Index");
        }

        public IActionResult Deletar(int id)
        {
            _contatoRepositorio.Apagar(id);
            return RedirectToAction("Index");
        }
    }
}

AplicacaoTeste/Controllers/HomeController.cs
using AplicacaoTeste.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AplicacaoTeste.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AplicacaoTeste/Views/Contatos/Criar.cshtml
@model ContatosModel

@{
    ViewData["Title"] = "Criar Contato";
}


<div class="text-center">
    <h1 class="display-4">Criar contato!</h1>
</div>
<form asp-controller="Contatos" asp-action="Criar" method="post"> 
    <div class="mb-3">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do Contato">
    </div>
    <div class="mb-3">
        <label for="telefone" class="form-label">Telefone</label>
        <input type="text" asp-for="Telefone" class="form-control" placeholder="Digite o telefone do Contato">
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Digite o email do Contato">
    </div>
    <div class="btn-group-lg" role="group" aria-label="Basic example">
        <button type="submit" class="btn btn-primary">Criar</button>
        <a type="button" class="btn btn-secondary" asp-controller="Contatos" asp-action="Index">Voltar</a>
    </div>
</form>

AplicacaoTeste/Views/Contatos/DeletarConfirmacao.cshtml
@model ContatosModel
@{
    ViewData["Title"] = "Deletar Contato";
}

<div class="text-center">
    <h1 class="display-4">Aviso!</h1>
    <p>Você tem certeza que gostaria de deletar o contato (@Model.Nome)?</p>
    <div class="btn-group-lg" role="group" aria-label="Basic example">
        <a type="button" class="btn btn-danger text-nowrap" style="width:100px" asp-controller="Contatos" asp-action="Deletar" asp-route-id="@Model.Id">Sim</a>
        <a type="button" class="btn btn-secondary" asp-controller="Contatos" asp-action="Index" >Cancelar</a>
</div>
</div>  

AplicacaoTeste/Views/Contatos/Editar.cshtml
@model ContatosModel
@{
    ViewData["Title"] = "Editar Contato";
}


<div class="text-center">
    <h1 class="display-4">Alterar contato!</h1>
</div>

<form asp-controller="Contatos" asp-action="Atualizar" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="mb-3">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do Contato">
    </div>
    <div class="mb-3">
        <label for="telefone" class="form-label">Telefone</label>
        <input type="text" asp-for="Telefone" class="form-control" placeholder="Digite o telefone do Contato">
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Digite o email do Contato">
    </div>
    <div class="btn-group-lg" role="group" aria-label="Basic example">
        <button type="submit" class="btn btn-primary">Editar</button>
        <a type="button" class="btn btn-secondary" asp-controller="Contatos" asp-action="Index">Voltar</a>
    </div>
</form>

AplicacaoTeste/Views/Contatos/Index.cshtml
@model List<ContatosModel>
@{
    ViewData["Title"] = "Lista de contatos";
}

<div class="text-center">
    <h1 class="display-4">Contatos</h1>
    <p>Bem vindo à lista de contatos</p>
</div>
<div>
    <a type="button" class="btn btn-primary btn-lg" asp-controller="Contatos" asp-action="Criar">Criar Contato</a>
</div>
<div class="text-center">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Telefone</th>
                <th scope="col">Email</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            @if (Model != null && Model.Any())
            {
                foreach(ContatosModel contato in Model)
                {
                    <tr>
                        <td>@contato.Nome</td>
                        <td>@contato.Telefone</td>
                        <td>@contato.Email</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" asp-route-id="@contato.Id" asp-controller="Contatos" asp-action="Editar"class="btn btn-primary">Editar</a>
                                <a role="button" asp-route-id="@contato.Id" asp-controller="Contatos" asp-action="DeletarConfirmacao" class="btn btn-danger">Deletar</a>
                            </div>
                        </td>
                    </tr>
                }
}
        </tbody>
    </table>
</div>

AplicacaoTeste/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo</h1>
    <p>Aplicativo de gerenciamento de Contatos.</p>
</div>

AplicacaoTeste/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cadastro de Usuários</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AplicacaoTeste.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lista de Contatos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contatos" asp-action="Index">Contatos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Lista de Contatos</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>